[package]
name = "phasic"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
rand = "0.8.5"
rodio = "0.20.1"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
zip = "2.2.2"
