[package]
name = "feusic"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
imgui = "0.12.0"
imgui-glow-renderer = "0.13.0"
imgui-winit-support = "0.13.0"
winit = { version = "0.30.0", default-features = false, features = [
    "rwh_05",
    "x11",
    "rwh_06",
] }
rand = "0.8.5"
rodio = "0.20.1"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
zip = "2.2.2"
glow = "0.14.0"
glutin = "0.32"
glutin-winit = "0.5.0"
