name: Release CI

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: Swatinem/rust-cache@v2

      - name: Build Windows
        run: cargo build --release --verbose

      - name: Run tests
        run: cargo test --release --verbose

      - name: Zip binaries on Windows
        run: powershell Compress-Archive -Path target/release/feusic.exe -DestinationPath feusic_windows.zip

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}
          path: |
            feusic_windows.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Download Windows build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts-windows-latest
          path: windows/
      - name: Create Release for Windows
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          files: windows/feusic_windows.zip
          name: Release
